### ISSUE TITLE
Save Count

### ISSUE THREAD

**Issue by QuintenQVD0** [silverben10/countable#10]
When i host the bot on heroku and the herocu crash and then restart you have to start counting at number 1. is there a possibility to add sqlite or just a file that stores the current count? so that when the bot reboots you can just continue counting? because now it is very annoying that you have to start over and the number is wrong.

**Comment by silverben10** [comment]
Hey! The bot already saves information like that to the disk using a package called `enmap` (which I think uses SQLite in the background).

I think the problem might be that, while Heroku does let you write to a disk when the bot's running, it clears all that data when the Heroku Dyno is restarted, so that would explain why the count is being lost when it crashes. Unfortunately there's not much I can do about that in terms of how the bot's coded.

If you want, you could try moving it to a different hosting platform like DigitalOcean? However, I'm not sure if they offer any free plans at the moment.

Alternatively, the bot does have a `set-count` command, which you could use for the moment to reset the count back to what it was before the crash?

**Comment by QuintenQVD0** [comment]
thx i will try that
